import BannerBottom from "@/components/BannerBottom";
import BannerTop from "@/components/BannerTop";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ItemCard from "@/components/ItemCard";
import Nav from "@/components/Nav";
import PersonalitiesList from "@/components/PersonalitiesList";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />
      <div className="max-centered">
        <BannerTop />
        <main role="main">
          <PersonalitiesList />
        </main>
        <BannerBottom />
        <Footer />
      </div>
    </>
  );
}
